// Code generated by sdkcodegen; DO NOT EDIT.

package workwx

// AsyncProgramResult 客服账号
type AsyncProgramResult struct {
	// ResponseErrCode 上报异步任务结果中上报的errcode。代表专区程序返回的错误码
	ResponseErrCode string `json:"response_errcode"`
	// ResponseData 上报异步任务结果中上报的result。代表专区程序的输出结果，为自定义的JSON字符串，要求与管理端配置的输出协议格式匹配
	ResponseData string `json:"response_data"`
}

// DebugModeStatusType 程序当前的调试模式状态
//
// 1为关闭
// 2为开启
type DebugModeStatusType int

const (
	// ExternalUserTypeWeChat 微信用户
	DebugModeStatusTypeOff DebugModeStatusType = 1
	// ExternalUserTypeWorkWeChat 企业微信用户
	DebugModeStatusTypeOn DebugModeStatusType = 2
)
